project:
  type: website
  output-dir: ../docs

website:
  title: "SOC-N100"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Syllabus
        href: syllabus.qmd
      - text: Resources
        href: resources.qmd
    tools:
      - icon: r-circle-fill
        href: https://stat20.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fevictionresearch%2FSOC-N100-Housing-Precarity&urlpath=rstudio%2F
        aria-label: RStudio

format:
  html:
    theme:
      light: [cosmo, light.scss]
      dark: [cosmo, dark.scss]
    css: styles.css
    toc: true

editor: visual

